### ISSUE TITLE
从java语言的activity用路由跳转到kotlin语言的activity会提示uri不存在，但是反过来就可以跳转成功

### ISSUE THREAD

**Issue by foryou96** [chenenyu/Router#114]
使用的是com.chenenyu.router:router:1.4.0-beta1

**Comment by chenenyu** [comment]
换一下最新版本试试，你这个版本有点久了

**Comment by foryou96** [comment]
下载了最新版的demo，gradle提示  Error:Extra properties['AAR'] are required.

**Comment by foryou96** [comment]
> 下载了最新版的demo，gradle提示 Error:Extra properties['AAR'] are required.

配置了NDK，可以编译了

**Comment by foryou96** [comment]
测试了最新版本的1.6.0的，也不能从java的跳转到kotlin的，并且从kotlin的跳转到java的会闪退报错
FATAL EXCEPTION: main
	Process: com.chenenyu.router.kotlin_app, PID: 19412
	java.lang.NoClassDefFoundError: Failed resolution of: Lcom/chenenyu/router/apt/Module1RouteTable;
	at com.chenenyu.router.AptHub.<clinit>(AptHub.java:34)
	at com.chenenyu.router.chain.IntentProcessor.intercept(IntentProcessor.java:32)
	at com.chenenyu.router.RealInterceptorChain.process(RealInterceptorChain.java:111)
	at com.chenenyu.router.chain.IntentValidator.intercept(IntentValidator.java:24)
	at com.chenenyu.router.RealInterceptorChain.process(RealInterceptorChain.java:111)
	at com.chenenyu.router.chain.BaseValidator.intercept(BaseValidator.java:41)
	at com.chenenyu.router.RealInterceptorChain.process(RealInterceptorChain.java:111)
	at com.chenenyu.router.RealRouter.getIntent(RealRouter.java:78)
	at com.chenenyu.router.RealRouter.go(RealRouter.java:85)
	at com.chenenyu.router.kotlin_app.MainActivity$onCreate$1.onClick(MainActivity.kt:16)
	at android.view.View.performClick(View.java:5265)
	at android.view.View$PerformClick.run(View.java:21534)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5765)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
	Caused by: java.lang.ClassNotFoundException: Didn't find class "com.chenenyu.router.apt.Module1RouteTable" on path: DexPathList[[zip file "/data/app/com.chenenyu.router.kotlin_app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.chenenyu.router.kotlin_app-1/lib/arm, /vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	at com.chenenyu.router.AptHub.<clinit>(AptHub.java:34) 
	at com.chenenyu.router.chain.IntentProcessor.intercept(IntentProcessor.java:32) 
	at com.chenenyu.router.RealInterceptorChain.process(RealInterceptorChain.java:111) 
	at com.chenenyu.router.chain.IntentValidator.intercept(IntentValidator.java:24) 
	at com.chenenyu.router.RealInterceptorChain.process(RealInterceptorChain.java:111) 
	at com.chenenyu.router.chain.BaseValidator.intercept(BaseValidator.java:41) 
	at com.chenenyu.router.RealInterceptorChain.process(RealInterceptorChain.java:111) 
	at com.chenenyu.router.RealRouter.getIntent(RealRouter.java:78) 
	at com.chenenyu.router.RealRouter.go(RealRouter.java:85) 
	at com.chenenyu.router.kotlin_app.MainActivity$onCreate$1.onClick(MainActivity.kt:16) 
	at android.view.View.performClick(View.java:5265) 
	at android.view.View$PerformClick.run(View.java:21534) 
	at android.os.Handler.handleCallback(Handler.java:815) 
	at android.os.Handler.dispatchMessage(Handler.java:104) 
	at android.os.Looper.loop(Looper.java:207) 
	at android.app.ActivityThread.main(ActivityThread.java:5765) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679) 
	Suppressed: java.lang.ClassNotFoundException: com.chenenyu.router.apt.Module1RouteTable
	at java.lang.Class.classForName(Native Method)
	at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
	at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
	... 20 more
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

在kotlin_app目录下创建了一个java语言的Main2Activity，并修改MainAcitivity中的跳转到test修改为main2，就会报错，AndroidManifest.xml中已有Main2Activity，直接startActivity(Intent(this, Main2Activity::class.java))可以跳转

**Comment by chenenyu** [comment]
我刚用demo测试了一下，并没有你说的这种情况。java kt混编是很早就支持的功能...

**Comment by foryou96** [comment]
找不到原因，可能开发环境的问题，换startActivity去启动了

**Comment by foryou96** [comment]
换成在Application中动态添加注解就可以了，按照demo的方式静态添加注解还是无效
Router.handleRouteTable(new RouteTable() {
            @Override
            public void handle(Map<String, Class<?>> map) {
                map.put("inboundMain", InboundMainActivity.class);
                map.put("firstMain", FirstMainActivity.class);
            }
        });

**Comment by chenenyu** [comment]
估计是你哪配置有问题  可以进群看看
