### ISSUE TITLE
编译时遇到java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by candyguy242** [chenenyu/Router#158]
版本1.7.5，各位编译配置均与demo中一致，但在运行时报出异常，编译过不去。请教如何解决。

* What went wrong:
Execution failed for task ':app:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)

Caused by: java.lang.RuntimeException: No option `moduleName` passed to Route annotation processor.
	at com.chenenyu.router.compiler.processor.RouteProcessor.process(RouteProcessor.java:86)
	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt)
	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:161)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:802)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:713)

**Comment by candyguy242** [comment]
> 看看gradle的配置

确实是gradle配置的问题，检查出来是因为项目中集成了Room框架，结果直接在gradle中添加了room的导出路径配置，把Router的参数给替换了，换了下面的配置就好了。

`
javaCompileOptions {
            annotationProcessorOptions {
                //为了兼容其他的注解处理器，不能直接为arguments赋值，比如Router框架也会向arguments中添加参数
                println("arguments:"+arguments)
                if(arguments == null){
                    arguments = ["room.schemaLocation":
                                         "$projectDir/schemas".toString()]
                }else{
                    arguments.put("room.schemaLocation","$projectDir/schemas".toString())
                }
                println("arguments:"+arguments)
            }

        }
`
