### ISSUE TITLE
较大概率会报NoClassDefFoundError 约千分之2左右概率

### ISSUE THREAD

**Issue by xxw8393** [chenenyu/Router#65]
Fatal Exception: java.lang.NoClassDefFoundError
Failed resolution of: Lxxxx/xx/x/PersonalFragmentN;
 Raw Text
com.xunmeng.router.AppRouteTable.handle (AppRouteTable.java:108)
com.xunmeng.router.AptHub.init (AptHub.java:76)
com.xunmeng.router.AptHub.initDefault (AptHub.java:58)
com.xunmeng.router.Router.initialize (Router.java:45)
com.xunmeng.router.Router.initialize (Router.java:32)

**Comment by chenenyu** [comment]
请问使用的是什么版本呢，这个统计是线上的统计吗？  方便的话可以加qq群详聊下

**Comment by cjdreamlive** [comment]
AndroidStudio has two application then one application will crash
UncaughtException detected: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/chenenyu/router/apt/AppRouteTable;
        at com.chenenyu.router.AptHub.<clinit>(AptHub.java:34)
        at com.chenenyu.router.chain.IntentProcessor.intercept(IntentProcessor.java:32)
        at com.chenenyu.router.RealInterceptorChain.process(RealInterceptorChain.java:111)
        at com.chenenyu.router.chain.IntentValidator.intercept(IntentValidator.java:24)
        at com.chenenyu.router.RealInterceptorChain.process(RealInterceptorChain.java:111)
        at com.chenenyu.router.chain.BaseValidator.intercept(BaseValidator.java:41)
        at com.chenenyu.router.RealInterceptorChain.process(RealInterceptorChain.java:111)
        at com.chenenyu.router.RealRouter.getIntent(RealRouter.java:78)

**Comment by chenenyu** [comment]
@cjdreamlive 你的意思是工程里面有两个`com.android.application`类型的module吗？

**Comment by cjdreamlive** [comment]
是的

chenenyu <notifications@github.com> 于2019年5月15日周三 下午9:01写道：
